### ISSUE TITLE
 api key error

### ISSUE THREAD

**Issue by kipilk0** [HarryJamesRobson/BitSnoop#1]
When type **y** or **n** have an a error.
```
python BitSnoop.py --bs 1GyJS5JeQMKm8zVcbwp6XUQCukrABV8Fts
Would you like to use an api key? (y/n) n
Traceback (most recent call last):
  File "BitSnoop.py", line 99, in <module>
    use_api = input("Would you like to use an api key? (y/n) ")
  File "<string>", line 1, in <module>
NameError: name 'n' is not defined
```

**Comment by HarryJamesRobson** [comment]
This is working for me, what version of Python are you running?

**Comment by kipilk0** [comment]
2.17
![изображение](https://user-images.githubusercontent.com/20616242/79785689-cc288600-8333-11ea-8365-5181f48fb042.png)


> 
> 
> This is working for me, what version of Python are you running?

**Comment by HarryJamesRobson** [comment]
That could be the problem as I don't think input is part of the 2.7 syntax. I'll update the readme to say that this is only tested on Python 3.8.
